const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Plugins.Mouse,
		C3.Plugins.Text,
		C3.Behaviors.solid,
		C3.Behaviors.Pin,
		C3.Plugins.Keyboard,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored
	];
};
self.C3_JsPropNameTable = [
	{TiledBackground: 0},
	{StartButton: 0},
	{Mouse: 0},
	{home: 0},
	{TiledBackground2: 0},
	{Solid: 0},
	{poin1: 0},
	{poin3: 0},
	{poin2: 0},
	{tile_: 0},
	{correctAnswer: 0},
	{Text: 0},
	{value15: 0},
	{Pin: 0},
	{jawaban1: 0},
	{value13: 0},
	{jawaban2: 0},
	{value12: 0},
	{jawabanbenar: 0},
	{TextFeedBack: 0},
	{TeksFeedBack2: 0},
	{TiledBackground3: 0},
	{kembali: 0},
	{Text2: 0},
	{teksakhir: 0},
	{game: 0},
	{bata: 0},
	{bata1: 0},
	{Keyboard: 0},
	{jawabanbenar2: 0},
	{TiledBackground4: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{door_: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{SelectedAnswer: 0},
	{score: 0},
	{CorrectAnswer1: 0},
	{LastX: 0},
	{LastY: 0},
	{sprite3_taken: 0},
	{sprite4_taken: 0},
	{sprite5_taken: 0},
	{sprite6_taken: 0},
	{sprite7_taken: 0}
];

self.InstanceType = {
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	StartButton: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	home: class extends self.ITextInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	poin1: class extends self.ISpriteInstance {},
	poin3: class extends self.ISpriteInstance {},
	poin2: class extends self.ISpriteInstance {},
	tile_: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	jawaban1: class extends self.ITextInstance {},
	jawaban2: class extends self.ITextInstance {},
	jawabanbenar: class extends self.ITextInstance {},
	TextFeedBack: class extends self.ITextInstance {},
	TeksFeedBack2: class extends self.ITextInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	kembali: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	teksakhir: class extends self.ITextInstance {},
	game: class extends self.ITextInstance {},
	bata: class extends self.ISpriteInstance {},
	bata1: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	jawabanbenar2: class extends self.ITextInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	door_: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {}
}